// Generated by fsmgen. DO NOT EDIT.
package example

import (
	"bytes"
	"context"
	"encoding/gob"
	"errors"
	"fmt"
	fsm "github.com/egoodhall/fsm"
	sqlc "github.com/egoodhall/fsm/gen/sqlc"
	"sync"
	"time"
)

const (
	TestMachineStateState1 fsm.State = "State1"
	TestMachineStateState2 fsm.State = "State2"
	TestMachineStateDone   fsm.State = "Done"
)

type TestMachineFSM interface {
	fsm.SupportsOptions
	Submit(ctx context.Context, int int) (fsm.TaskID, error)
}

func NewTestMachineFSMBuilder() TestMachineFSMBuilder_State1Stage {
	return new(testMachineFSM)
}

type State1Transitions interface {
	ToState2(context.Context, int) error
}

type State2Transitions interface {
	ToDone(context.Context) error
}

type TestMachineFSMBuilder_State1Stage interface {
	FromState1(func(context.Context, State1Transitions, int) error) TestMachineFSMBuilder_State2Stage
}

type TestMachineFSMBuilder_State2Stage interface {
	FromState2(func(context.Context, State2Transitions, int) error) TestMachineFSMBuilder__FinalStage
}

type TestMachineFSMBuilder_DoneStage interface {
	FromDone(func(context.Context) error) TestMachineFSMBuilder__FinalStage
}

type TestMachineFSMBuilder__FinalStage interface {
	BuildAndStart(context.Context, ...fsm.Option) (TestMachineFSM, error)
}

// FSM type checks
var _ TestMachineFSM = new(testMachineFSM)
var _ fsm.SupportsOptions = new(testMachineFSM)
var _ TestMachineFSMBuilder_State1Stage = new(testMachineFSM)
var _ TestMachineFSMBuilder_State2Stage = new(testMachineFSM)
var _ TestMachineFSMBuilder__FinalStage = new(testMachineFSM)
var _ State1Transitions = new(testMachineFSM)
var _ State2Transitions = new(testMachineFSM)

// TestMachineFSM implementation
type testMachineFSM_State1Params struct {
	ID      fsm.TaskID
	Attempt int
	P0      int
}

type testMachineFSM_State2Params struct {
	ID      fsm.TaskID
	Attempt int
	P0      int
}

type testMachineFSM_DoneParams struct {
	ID      fsm.TaskID
	Attempt int
}

type testMachineFSM struct {
	lock sync.Mutex
	ctx  context.Context

	// Configuration options
	store        fsm.Store
	onTransition fsm.TransitionListener
	onCompletion fsm.CompletionListener
	backoff      fsm.Backoff

	// FSM state transitions
	state1State func(context.Context, State1Transitions, int) error
	state2State func(context.Context, State2Transitions, int) error

	// FSM queues
	state1Queue chan testMachineFSM_State1Params
	state2Queue chan testMachineFSM_State2Params
	doneQueue   chan testMachineFSM_DoneParams
}

// FSM builder methods

func (f *testMachineFSM) FromState1(fn func(context.Context, State1Transitions, int) error) TestMachineFSMBuilder_State2Stage {
	f.state1State = fn
	return f
}

func (f *testMachineFSM) FromState2(fn func(context.Context, State2Transitions, int) error) TestMachineFSMBuilder__FinalStage {
	f.state2State = fn
	return f
}

func (f *testMachineFSM) BuildAndStart(ctx context.Context, opts ...fsm.Option) (TestMachineFSM, error) {
	// Check if FSM is already started
	if !f.lock.TryLock() {
		return nil, errors.New("FSM already started")
	}

	// Set context
	f.ctx = ctx

	// Initialize state queues
	f.state1Queue = make(chan testMachineFSM_State1Params, 5)
	f.state2Queue = make(chan testMachineFSM_State2Params, 5)
	f.doneQueue = make(chan testMachineFSM_DoneParams, 5)

	// Apply options
	for _, opt := range opts {
		if err := opt(f); err != nil {
			return nil, err
		}
	}
	if f.store == nil {
		if store, err := fsm.InMemory()(); err != nil {
			return nil, err
		} else {
			f.store = store
		}
	}
	if f.backoff == nil {
		f.backoff = fsm.LinearBackoff(500*time.Millisecond, 30*time.Second)
	}

	// Start FSM processors
	// Start 0 state1Processor processors
	for i := 0; i < 0; i++ {
		go f.state1Processor()
	}
	go f.state1Processor()
	// Start 5 state2Processor processors
	for i := 0; i < 5; i++ {
		go f.state2Processor()
	}
	go f.state2Processor()
	// Start 0 doneProcessor processors
	for i := 0; i < 0; i++ {
		go f.doneProcessor()
	}
	go f.doneProcessor()

	// Resume existingtasks
	if err := f.resumeTasks(); err != nil {
		return nil, err
	}
	return f, nil
}

func (f *testMachineFSM) resumeTasks() error {
	tasks, err := f.store.Q().ListTasks(f.ctx)
	if err != nil {
		return err
	}
	for _, task := range tasks {
		transition, err := f.store.Q().GetLastValidTransition(f.ctx, task.ID)
		if err != nil {
			return err
		}

		switch fsm.State(transition.ToState) {
		case TestMachineStateState1:
			var msg testMachineFSM_State1Params
			if err := gob.NewDecoder(bytes.NewReader(task.Data)).Decode(&msg); err != nil {
				return err
			}
			fsm.Logger(f.ctx).Info("Resuming task", "id", task.ID)
			select {
			case f.state1Queue <- msg:
				return nil
			case <-f.ctx.Done():
				return errors.New("task submission cancelled")
			}
		case TestMachineStateState2:
			var msg testMachineFSM_State2Params
			if err := gob.NewDecoder(bytes.NewReader(task.Data)).Decode(&msg); err != nil {
				return err
			}
			fsm.Logger(f.ctx).Info("Resuming task", "id", task.ID)
			select {
			case f.state2Queue <- msg:
				return nil
			case <-f.ctx.Done():
				return errors.New("task submission cancelled")
			}
		}
	}
	return nil
}

// FSM options

func (f *testMachineFSM) WithStore(store fsm.Store) {
	f.store = store
}

func (f *testMachineFSM) WithContext(update func(context.Context) context.Context) {
	f.ctx = update(f.ctx)
}

func (f *testMachineFSM) WithTransitionListener(listener fsm.TransitionListener) {
	f.onTransition = listener
}

func (f *testMachineFSM) WithCompletionListener(listener fsm.CompletionListener) {
	f.onCompletion = listener
}

func (f *testMachineFSM) WithBackoff(backoff fsm.Backoff) {
	f.backoff = backoff
}

// FSM transition methods

func (f *testMachineFSM) ToState1(ctx context.Context, P0 int) error {
	id := fsm.GetTaskID(ctx)
	fromState := fsm.GetState(ctx)
	toState := fsm.State(TestMachineStateState1)
	msg := testMachineFSM_State1Params{ID: id, P0: P0}

	buf := new(bytes.Buffer)
	if err := gob.NewEncoder(buf).Encode(msg); err != nil {
		return err
	}

	if err := f.store.Q().RecordTransition(ctx, sqlc.RecordTransitionParams{
		TaskID:    int64(id),
		Attempt:   int64(fsm.GetAttempt(ctx)),
		FromState: string(fromState),
		ToState:   string(toState),
		Data:      buf.Bytes(),
	}); err != nil {
		return err
	}
	fsm.Logger(ctx).Debug("Transitioned state", "id", id, "from", fromState, "to", toState)
	if f.onTransition != nil {
		f.onTransition(ctx, msg.ID, fromState, toState)
	}

	select {
	case f.state1Queue <- msg:
		return nil
	case <-ctx.Done():
		return fmt.Errorf("task submission cancelled: id = %d", id)
	}
}

func (f *testMachineFSM) ToState2(ctx context.Context, P0 int) error {
	id := fsm.GetTaskID(ctx)
	fromState := fsm.GetState(ctx)
	toState := fsm.State(TestMachineStateState2)
	msg := testMachineFSM_State2Params{ID: id, P0: P0}

	buf := new(bytes.Buffer)
	if err := gob.NewEncoder(buf).Encode(msg); err != nil {
		return err
	}

	if err := f.store.Q().RecordTransition(ctx, sqlc.RecordTransitionParams{
		TaskID:    int64(id),
		Attempt:   int64(fsm.GetAttempt(ctx)),
		FromState: string(fromState),
		ToState:   string(toState),
		Data:      buf.Bytes(),
	}); err != nil {
		return err
	}
	fsm.Logger(ctx).Debug("Transitioned state", "id", id, "from", fromState, "to", toState)
	if f.onTransition != nil {
		f.onTransition(ctx, msg.ID, fromState, toState)
	}

	select {
	case f.state2Queue <- msg:
		return nil
	case <-ctx.Done():
		return fmt.Errorf("task submission cancelled: id = %d", id)
	}
}

func (f *testMachineFSM) ToDone(ctx context.Context) error {
	id := fsm.GetTaskID(ctx)
	fromState := fsm.GetState(ctx)
	toState := fsm.State(TestMachineStateDone)
	msg := testMachineFSM_DoneParams{ID: id}

	buf := new(bytes.Buffer)
	if err := gob.NewEncoder(buf).Encode(msg); err != nil {
		return err
	}

	if err := f.store.Q().RecordTransition(ctx, sqlc.RecordTransitionParams{
		TaskID:    int64(id),
		Attempt:   int64(fsm.GetAttempt(ctx)),
		FromState: string(fromState),
		ToState:   string(toState),
		Data:      buf.Bytes(),
	}); err != nil {
		return err
	}
	fsm.Logger(ctx).Debug("Transitioned state", "id", id, "from", fromState, "to", toState)
	if f.onTransition != nil {
		f.onTransition(ctx, msg.ID, fromState, toState)
	}

	select {
	case f.doneQueue <- msg:
		return nil
	case <-ctx.Done():
		return fmt.Errorf("task submission cancelled: id = %d", id)
	}
}

func (f *testMachineFSM) state1Processor() {
	ctx := fsm.PutState(f.ctx, fsm.State(TestMachineStateState1))
	for msg := range f.state1Queue {
		ctx2 := fsm.PutAttempt(ctx, msg.Attempt)
		fsm.Logger(ctx2).Debug("Processing message", "id", msg.ID, "attempt", msg.Attempt, "state", TestMachineStateState1)
		if err := f.state1State(fsm.PutTaskID(ctx2, msg.ID), f, msg.P0); err != nil {
			msg.Attempt++
			delay := f.backoff(msg.Attempt)
			fsm.Logger(ctx).Debug("Processing error", "id", msg.ID, "attempt", msg.Attempt, "delay", delay, "state", TestMachineStateState1, "error", err)
			if err := f.store.Q().RecordTransition(ctx2, sqlc.RecordTransitionParams{
				TaskID:    int64(msg.ID),
				Attempt:   int64(msg.Attempt),
				FromState: string(TestMachineStateState1),
				ToState:   string(fsm.StateError),
				Data:      []byte(err.Error()),
			}); err != nil {
				fsm.Logger(ctx).Debug("Failed to record transition", "id", msg.ID, "attempt", msg.Attempt, "delay", delay, "state", TestMachineStateState1, "error", err)
			}

			go func() {
				<-time.After(delay)
				select {
				case f.state1Queue <- msg:
				case <-ctx.Done():
				}
			}()
		}
	}
}

func (f *testMachineFSM) state2Processor() {
	ctx := fsm.PutState(f.ctx, fsm.State(TestMachineStateState2))
	for msg := range f.state2Queue {
		ctx2 := fsm.PutAttempt(ctx, msg.Attempt)
		fsm.Logger(ctx2).Debug("Processing message", "id", msg.ID, "attempt", msg.Attempt, "state", TestMachineStateState2)
		if err := f.state2State(fsm.PutTaskID(ctx2, msg.ID), f, msg.P0); err != nil {
			msg.Attempt++
			delay := f.backoff(msg.Attempt)
			fsm.Logger(ctx).Debug("Processing error", "id", msg.ID, "attempt", msg.Attempt, "delay", delay, "state", TestMachineStateState2, "error", err)
			if err := f.store.Q().RecordTransition(ctx2, sqlc.RecordTransitionParams{
				TaskID:    int64(msg.ID),
				Attempt:   int64(msg.Attempt),
				FromState: string(TestMachineStateState2),
				ToState:   string(fsm.StateError),
				Data:      []byte(err.Error()),
			}); err != nil {
				fsm.Logger(ctx).Debug("Failed to record transition", "id", msg.ID, "attempt", msg.Attempt, "delay", delay, "state", TestMachineStateState2, "error", err)
			}

			go func() {
				<-time.After(delay)
				select {
				case f.state2Queue <- msg:
				case <-ctx.Done():
				}
			}()
		}
	}
}

func (f *testMachineFSM) doneProcessor() {
	ctx := fsm.PutState(f.ctx, fsm.State(TestMachineStateDone))
	for msg := range f.doneQueue {
		if f.onCompletion != nil {
			f.onCompletion(ctx, msg.ID, fsm.State(TestMachineStateDone))
		}
	}
}

// Submit FSM tasks

func (f *testMachineFSM) Submit(ctx context.Context, P0 int) (fsm.TaskID, error) {
	msg := testMachineFSM_State1Params{P0: P0}

	buf := new(bytes.Buffer)
	if err := gob.NewEncoder(buf).Encode(msg); err != nil {
		return 0, err
	}

	task, err := f.store.Q().CreateTask(ctx, buf.Bytes())
	if err != nil {
		return 0, err
	}
	msg.ID = fsm.TaskID(task.ID)

	select {
	case f.state1Queue <- msg:
		return msg.ID, nil
	case <-ctx.Done():
		return 0, errors.New("task submission cancelled")
	}
}
